version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"  
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://shreyash123:Shreyash12345678@docdb-2024-12-27-13-26-24.cluster-c7c06gw6inza.us-east-2.docdb.amazonaws.com:27017/Slotfixing?ssl=true&sslInvalidHostNameAllowed=true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
